name: CI
on:
  push:
    tags:
      - '*.*.*'
env:
  nim-version: 'stable'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ env.nim-version }}
      - run: nimble test -Y